<?php

/**
 * @file
 * Contains migration_dashboard.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function migration_dashboard_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the migration_dashboard module.
    case 'help.page.migration_dashboard':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migration Dashboard') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function migration_dashboard_theme($theme) {
  return [
    'migration_dashboard' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_page_attachments_alter().
 *
 * This is taken from the awesome setup by Sam Mortenson:
 * @link https://thinkshout.com/blog/2019/10/adding-webpack-to-a-traditional-drupal-theme/
 */
// function migration_dashboard_page_attachments_alter(array &$attachments) {
//   // Use the dev library if we're developing locally.
//   if (in_array('migration_dashboard/dashboard', $attachments['#attached']['library']) && file_exists(__DIR__ . '/js')) {
//     $index = array_search('migration_dashboard/dashboard', $attachments['#attached']['library']);
//     // $attachments['#attached']['library'][$index] = 'migration_dashboard/react_app_dev';
//   }
// }